[package]
name = "integrity-check"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
rusqlite = "0.38.0"
sha2 = "0.10.9"
tempfile = "3.24.0"
